name: codeatlas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  archive: ^3.6.1
  firebase_storage: ^12.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 23
  remove_alpha_ios: true
  image_path: "assets/icon/icon_app.png"
  adaptive_icon_background: "#0B1220"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
