// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX-Y32RxJenVWMtt9yxyol1-Y-60vG70I',
    appId: '1:968774301622:web:d6a9bd424c920c8ffc7317',
    messagingSenderId: '968774301622',
    projectId: 'codeatlas-11ef5',
    authDomain: 'codeatlas-11ef5.firebaseapp.com',
    storageBucket: 'codeatlas-11ef5.firebasestorage.app',
    measurementId: 'G-DMKRJLX81R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQV3a5cf2i3SPQbNav77ozuzbj0vc1Uqg',
    appId: '1:968774301622:android:c870cd7c0008fb7ffc7317',
    messagingSenderId: '968774301622',
    projectId: 'codeatlas-11ef5',
    storageBucket: 'codeatlas-11ef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKZF1vhK-mdDSZKHTjBBcqzdqIN64cZ1w',
    appId: '1:968774301622:ios:ca2d28d2d92cff69fc7317',
    messagingSenderId: '968774301622',
    projectId: 'codeatlas-11ef5',
    storageBucket: 'codeatlas-11ef5.firebasestorage.app',
    iosBundleId: 'com.example.codeatlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKZF1vhK-mdDSZKHTjBBcqzdqIN64cZ1w',
    appId: '1:968774301622:ios:ca2d28d2d92cff69fc7317',
    messagingSenderId: '968774301622',
    projectId: 'codeatlas-11ef5',
    storageBucket: 'codeatlas-11ef5.firebasestorage.app',
    iosBundleId: 'com.example.codeatlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX-Y32RxJenVWMtt9yxyol1-Y-60vG70I',
    appId: '1:968774301622:web:6e3cf449f8e7a2a2fc7317',
    messagingSenderId: '968774301622',
    projectId: 'codeatlas-11ef5',
    authDomain: 'codeatlas-11ef5.firebaseapp.com',
    storageBucket: 'codeatlas-11ef5.firebasestorage.app',
    measurementId: 'G-LWGH24C96P',
  );
}
